name: App

on: [push]

jobs:
  build-scheduler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build scheduler image
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: ${{ github.repository }}/scheduler
          dockerfile: deployment/docker/scheduler/Dockerfile
          tag_with_sha: true
          tag_with_ref: true