name: App

on:
  push:
    tags:
      - '*'

jobs:
  build-scheduler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: deployment/docker/scheduler/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/scheduler:${{ steps.meta.outputs.version }}